version: '3'
services:
  nats:
    image: nats-streaming
    restart: always
    
  api:
    build:
      context: algorithmAPI
    image: frlnbrg/project_hopper_algorithm_api
    ports:
      - "3000:3000"
    restart: always
    
  algorithm-aggregate:
    build:
      context: algorithm
    image: frlnbrg/project_hopper_algorithm_aggregate    
    restart: always

  eventstore:
    build:
      context: eventstore
    image: frlnbrg/project_hopper_event_store    
    restart: always

  querystore:
    build:
      context: algorithmQueryStore
    image: frlnbrg/algorithm_query_store
    restart: always